name: Test action

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - subject: 每日天气推送
            attachments: action.yml
            body: |
              first line
              second line
          - subject: 每日天气示例
            attachments: package.json,package-lock.json
            html_body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>Heading</h1>
              <p>Paragraph</p>
              </body>
              </html>
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Send mail
        uses: ./
        with:
          server_address: ${{secrets.ADDRESS}}
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{matrix.subject}}
          body: ${{matrix.body}}
          html_body: ${{matrix.html_body}}
          to: ${{github.event.pusher.email}}
          from: github-actions
          attachments: ${{matrix.attachments}}
          priority: high
          isWeather: true,
          weatherKey: '${{secrets.WEATHERKEY}}'
          location: '${{secrets.LOCATION}}'
          startDay: '2020-10-01'

  url-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Send mail
        uses: ./
        with:
          connection_url: smtp+starttls://${{secrets.USERNAME}}:${{secrets.PASSWORD}}@${{secrets.ADDRESS}}/
          subject: Plain body with connection_url
          body: |
            first line
            second line
          to: ${{github.event.pusher.email}}
          from: github-actions